name: Generate XoDos bootstrap archives

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions: {} # default none

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  TERMUX_APP_PACKAGE: com.xodos

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64
          # add other arches if needed: arm, i686, x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
       
      - name: Patch Termux app package (prefix source)
        run: |
         sed -i \
          's/^TERMUX_APP_PACKAGE="com.termux"/TERMUX_APP_PACKAGE="com.xodos"/' \
           scripts/properties.sh

      - name: Verify Termux prefix
        run: |
          source scripts/properties.sh
           echo "TERMUX_APP_PACKAGE=$TERMUX_APP_PACKAGE"
           echo "TERMUX_PREFIX=$TERMUX_PREFIX"
           echo "TERMUX_HOME=$TERMUX_HOME"


        
      - name: Build bootstrap
        run: ./scripts/generate-bootstraps.sh --architectures ${{ matrix.arch }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap-archives-${{ matrix.arch }}-${{ github.sha }}
          path: "*.zip"

  publish:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ./
      - name: Create release tag
        id: get_tag
        run: |
          new_tag="xodos-bootstrap2-$(date '+%Y.%m.%d')"
          git tag "$new_tag"
          git push --tags
          echo "tag_name=$new_tag" >> $GITHUB_OUTPUT
      - name: Publish bootstrap zips to GitHub release
        uses: termux/upload-release-action@v4.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.zip"
          file_glob: true
          release_name: "XoDos bootstrap archives"
          tag: ${{ steps.get_tag.outputs.tag_name }}
          checksums: sha256,sha512,md5
